language: python
python:
  - "2.7"
install:
  - "pip install coveralls"
  - "pip install -r requirements_test.txt"
script: "coverage run --source='.' --omit='scripts/*,bars_django/wsgi.py,bars_django/settings/*,*/migrations/*,*/__init__.py,manage.py' manage.py test"
after_success: coveralls

notifications:
  slack: chocapix:KsJ6bP6EWXpLQGh1RrkgquXO
