language: python
python:
  - "3.4"
install:
  - "pip3 install coveralls"
  - "pip3 install -r requirements_test.txt"
script: "coverage run --source='.' --omit='scripts/*,bars_django/wsgi.py,bars_django/settings/prod.py' manage.py test"
after_success: coveralls

notifications:
  irc:
    channels:
      - "irc.rezosup.org#bars"
    template:
      - "%{repository_name}/%{branch} %{commit} %{author}: %{message}"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
