language: python
python:
  - "2.7"
  - "3.4"
install:
  - "pip install coveralls"
  - "pip install -r requirements_test.txt"
script: "coverage run --source='.' --omit='scripts/*,bars_django/wsgi.py,bars_django/settings/*,*/migrations/*,*/__init__.py,manage.py' manage.py test"
after_success: coveralls

notifications:
  irc:
    channels:
      - "irc.rezosup.org#chocapix"
    template:
      - "%{repository_name}/%{branch} %{commit} %{author}: %{message}"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
  slack: chocapix:KsJ6bP6EWXpLQGh1RrkgquXO
