language: python
python:
  - "2.7"
install:
  - "pip install coveralls"
  - "pip install -r requirements.txt"
script: "coverage run --source='.' --omit='scripts/*,bars_django/wsgi.py,bars_django/settings/prod.py' manage.py test"
after_success: coveralls

notifications:
  irc:
    channels:
      - "irc.rezosup.org#bars"
    skip_join: true
